### ISSUE TITLE
Wrong letter

### ISSUE THREAD

**Issue by Nekro64** [rascada/study-words#4]
W słowie "podnosić" w trzeciej formie jest "hat gehobem" zamiast "hat gehoben"
Błąd jest na finalnej wersji na stronie words.thatonly.me

**Comment by rascada** [comment]
![przechwytywanie](https://cloud.githubusercontent.com/assets/10521222/13043992/ec49b31c-d3cb-11e5-9647-1c2545ba188d.PNG)
